// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qUna1WAqo7DhB55Hm06d12JS4cgZszg',
    appId: '1:965049742008:web:f534a13140a8c164ab7a4d',
    messagingSenderId: '965049742008',
    projectId: 'sec4youapp',
    authDomain: 'sec4youapp.firebaseapp.com',
    storageBucket: 'sec4youapp.firebasestorage.app',
    measurementId: 'G-DC92DZ4V6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWstCnkV8LSrUVa4AnWhWC6er-_XzZJ8',
    appId: '1:965049742008:android:964d2f69911b1905ab7a4d',
    messagingSenderId: '965049742008',
    projectId: 'sec4youapp',
    storageBucket: 'sec4youapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSK8KIu2dFHNyYumj1yNDU5jHEkVGzt6Y',
    appId: '1:965049742008:ios:a79243cc0ec2b894ab7a4d',
    messagingSenderId: '965049742008',
    projectId: 'sec4youapp',
    storageBucket: 'sec4youapp.firebasestorage.app',
    iosBundleId: 'com.example.chatbotSec4you',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSK8KIu2dFHNyYumj1yNDU5jHEkVGzt6Y',
    appId: '1:965049742008:ios:a79243cc0ec2b894ab7a4d',
    messagingSenderId: '965049742008',
    projectId: 'sec4youapp',
    storageBucket: 'sec4youapp.firebasestorage.app',
    iosBundleId: 'com.example.chatbotSec4you',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7qUna1WAqo7DhB55Hm06d12JS4cgZszg',
    appId: '1:965049742008:web:0161beee8fb2c2f1ab7a4d',
    messagingSenderId: '965049742008',
    projectId: 'sec4youapp',
    authDomain: 'sec4youapp.firebaseapp.com',
    storageBucket: 'sec4youapp.firebasestorage.app',
    measurementId: 'G-WR67G3CLCF',
  );
}
